### PR TITLE
Added necessary documentation for the new features

### PR DESCRIPTION
**Pull request by kkomelin**

### CODE REVIEW

**Comment by thomasjsn** [comment]
Looks good, a couple of minor tweaks needed. But I can take care of that. I'll merge it tonight :+1: Thanks for helping out!

How did the query testing go?

**Comment by kkomelin** [comment]
@thomasjsn Thanks for reviewing the PR.

> Looks good, a couple of minor tweaks needed. But I can take care of that. I'll merge it tonight :+1: Thanks for helping out!

My pleasure.

> How did the query testing go?

The elasticSearch() works well. However, it's not very suitable for my case because I don't have any query string and I just need to search by a set of parameters, such as date ranges and geospatical indexes. So, as I understand, I have to write my own Engine or use a package with more extensive search features, such as https://github.com/basemkhirat/elasticsearch At least, I need a possibility to write raw queries and then match the results with Eloquent models as Scout does.

Anyway, your improvements for laravel-scout-elastic are useful too, so thanks for them.

**Comment by thomasjsn** [comment]
Aha, I see. I did consider moving the configurable query parameters "down one level", but so far I have decided against it. It's really a complexity vs. ease of use consideration.

My understanding is that a lot of developers is using Scout for importing and the model observer, but have implemented custom ways of searching. To really be able to use everything that Elasticsearch has to offer, I think that is necessary.

**Comment by kkomelin** [comment]
Thank you @thomasjsn for your opinion. Yes, I agree, we need to write our own search mechanisms for complex cases, such as mine.

**Comment by kkomelin** [comment]
Thanks @thomasjsn

**Pull request merged**
